"""Added owner_id to habits

Revision ID: 13439207009a
Revises: 185ef7945e0f
Create Date: 2023-07-12 18:17:27.222900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13439207009a'
down_revision = '185ef7945e0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'habits', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'owner_id')
    # ### end Alembic commands ###
