"""Added created_at for habit

Revision ID: 42d475821643
Revises: 84b1e640fc6d
Create Date: 2023-07-18 09:27:33.126912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d475821643'
down_revision = '84b1e640fc6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'created_at')
    # ### end Alembic commands ###
