"""Added comment for habit

Revision ID: 6c4132fd3e56
Revises: 42d475821643
Create Date: 2023-08-02 17:28:54.329576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4132fd3e56'
down_revision = '42d475821643'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_completions', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_completions', 'comment')
    # ### end Alembic commands ###
