"""brand new database

Revision ID: 630dfee16977
Revises: 
Create Date: 2023-08-02 22:14:28.830327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630dfee16977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public', sa.String(), nullable = False),
    sa.Column('frequency', sa.String(), nullable = False),
    sa.Column('habit_description', sa.String(), nullable = False),
    sa.Column('end_goal', sa.String(), nullable = False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable = False),
    sa.Column('owner_id', sa.Integer(), nullable = False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable = False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable = False),
    sa.Column('comment', sa.String(), nullable = True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'habit_id', name='unique_habit_completion_per_day')
    )
    op.create_index(op.f('ix_habit_completions_id'), 'habit_completions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_completions_id'), table_name='habit_completions')
    op.drop_table('habit_completions')
    op.drop_table('habits')
    op.drop_table('users')
    # ### end Alembic commands ###
