"""cascade

Revision ID: ae6282c4e813
Revises: 630dfee16977
Create Date: 2023-08-02 23:06:15.385031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6282c4e813'
down_revision = '630dfee16977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('habit_completions_habit_id_fkey', 'habit_completions', type_='foreignkey')
    op.create_foreign_key(None, 'habit_completions', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_completions', type_='foreignkey')
    op.create_foreign_key('habit_completions_habit_id_fkey', 'habit_completions', 'habits', ['habit_id'], ['id'])

    # ### end Alembic commands ###
