"""added values until end date

Revision ID: edb11fd5fde8
Revises: ae6282c4e813
Create Date: 2023-08-04 20:47:23.223000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb11fd5fde8'
down_revision = 'ae6282c4e813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit_completions', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit_completions', 'habit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
